### PR TITLE
Dockerization

### PR DESCRIPTION
**Pull request by DevAleks**

### CODE REVIEW

**Comment by HadesArchitect** [comment]
node_modules must be in git ignore, package-lock.json should not be in gitignore.

**Comment by DevAleks** [comment]
node_modules must be in the Angular src area, because it created once time with other app files. For recreate node_modules I must rebuild large amount of other app files. It is a wrong way, I suppose.

**Comment by HadesArchitect** [comment]
Node_modules should be there on runtime, not in the source code.

**Comment by DevAleks** [comment]
U have been absolutely right about node_modules. Fixed it!

**Pull request merged**
